FROM python:3.9-slim

# 在容器里创建一个工作目录
WORKDIR /app

# 复制项目文件到容器内
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# 如果你的 Flask 程序文件是 app.py，则这样启动
EXPOSE 80
CMD ["python", "app.py"]
